name: Build Docker Image and Print Jar File Path

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Print Jar File Path
      run: |
        cd target
        ls -l *.jar | awk '{print $9}'
        JAR_FILE=$(ls -1 *.jar)
        echo "Jar file path: ${PWD}/${JAR_FILE}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker login -u cloudtechmasters -pManager#436
    - name: Build and Push Docker Image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t cloudtechmasters/springboot-maven-course-micro-svc:latest --push .

    - name: List Docker Images
      run: docker images
